// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// A `CalendarPeriod` represents the abstract concept of a time period that has
/// a canonical start. Grammatically, "the start of the current
/// `CalendarPeriod`." All calendar times begin at midnight UTC.
public enum CalendarPeriod: Int, Codable, Equatable, Sendable {
  case unspecified = 0
  case day = 1
  case week = 2
  case fortnight = 3
  case month = 4
  case quarter = 5
  case half = 6
  case year = 7

  public init() {
    self = .unspecified
  }

  public var stringValue: String {
    switch self {
    case .unspecified: return "CALENDAR_PERIOD_UNSPECIFIED"
    case .day: return "DAY"
    case .week: return "WEEK"
    case .fortnight: return "FORTNIGHT"
    case .month: return "MONTH"
    case .quarter: return "QUARTER"
    case .half: return "HALF"
    case .year: return "YEAR"
    }
  }

  public init?(stringValue: String) {
    switch stringValue {
    case "CALENDAR_PERIOD_UNSPECIFIED": self = .unspecified
    case "DAY": self = .day
    case "WEEK": self = .week
    case "FORTNIGHT": self = .fortnight
    case "MONTH": self = .month
    case "QUARTER": self = .quarter
    case "HALF": self = .half
    case "YEAR": self = .year
    default: return nil
    }
  }
}
