// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents a whole or partial calendar date, such as a birthday. The time of
/// day and time zone are either specified elsewhere or are insignificant. The
/// date is relative to the Gregorian Calendar. This can represent one of the
/// following:
///
/// * A full date, with non-zero year, month, and day values.
/// * A month and day, with a zero year (for example, an anniversary).
/// * A year on its own, with a zero month and a zero day.
/// * A year and month, with a zero day (for example, a credit card expiration
///   date).
///
/// Related types:
///
/// * [google.type.TimeOfDay][google.type.TimeOfDay]
/// * [google.type.DateTime][google.type.DateTime]
/// * [google.protobuf.Timestamp][google.protobuf.Timestamp]
///
/// [google.protobuf.Timestamp]: https://www.google.com/search?q=Swift+google.protobuf+GoogleWKT.Timestamp
/// [google.type.DateTime]: <doc:DateTime>
/// [google.type.TimeOfDay]: <doc:TimeOfDay>
public struct Date: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Year of the date. Must be from 1 to 9999, or 0 to specify a date without
  /// a year.
  public var year: Swift.Int32 = Swift.Int32()

  /// Month of a year. Must be from 1 to 12, or 0 to specify a year without a
  /// month and day.
  public var month: Swift.Int32 = Swift.Int32()

  /// Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
  /// to specify a year by itself or a year and month where the day isn't
  /// significant.
  public var day: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Date`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Date().with { $0.year = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let year = CodingKeys(stringValue: "year")
    static let month = CodingKeys(stringValue: "month")
    static let day = CodingKeys(stringValue: "day")

    static let _knownKeys: Set<Swift.String> = [
      "year",
      "month",
      "day",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .year) {
      self.year = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .month) {
      self.month = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .day) {
      self.day = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.year, forKey: .year)
    try container.encode(self.month, forKey: .month)
    try container.encode(self.day, forKey: .day)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.type.Date"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
