// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents civil time (or occasionally physical time).
///
/// This type can represent a civil time in one of a few possible ways:
///
///  * When utc_offset is set and time_zone is unset: a civil time on a calendar
///    day with a particular offset from UTC.
///  * When time_zone is set and utc_offset is unset: a civil time on a calendar
///    day in a particular time zone.
///  * When neither time_zone nor utc_offset is set: a civil time on a calendar
///    day in local time.
///
/// The date is relative to the Proleptic Gregorian Calendar.
///
/// If year is 0, the DateTime is considered not to have a specific year. month
/// and day must have valid, non-zero values.
///
/// This type may also be used to represent a physical time if all the date and
/// time fields are set and either case of the `time_offset` oneof is set.
/// Consider using `Timestamp` message for physical time instead. If your use
/// case also would like to store the user's timezone, that can be done in
/// another field.
///
/// This type is more flexible than some applications may want. Make sure to
/// document and validate your application's limitations.
public struct DateTime: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Year of date. Must be from 1 to 9999, or 0 if specifying a
  /// datetime without a year.
  public var year: Int32

  /// Required. Month of year. Must be from 1 to 12.
  public var month: Int32

  /// Required. Day of month. Must be from 1 to 31 and valid for the year and
  /// month.
  public var day: Int32

  /// Required. Hours of day in 24 hour format. Should be from 0 to 23. An API
  /// may choose to allow the value "24:00:00" for scenarios like business
  /// closing time.
  public var hours: Int32

  /// Required. Minutes of hour of day. Must be from 0 to 59.
  public var minutes: Int32

  /// Required. Seconds of minutes of the time. Must normally be from 0 to 59. An
  /// API may allow the value 60 if it allows leap-seconds.
  public var seconds: Int32

  /// Required. Fractions of seconds in nanoseconds. Must be from 0 to
  /// 999,999,999.
  public var nanos: Int32

  /// Optional. Specifies either the UTC offset or the time zone of the DateTime.
  /// Choose carefully between them, considering that time zone data may change
  /// in the future (for example, a country modifies their DST start/end dates,
  /// and future DateTimes in the affected range had already been stored).
  /// If omitted, the DateTime is considered to be in local time.
  public var timeOffset: OneOf_TimeOffset?

  /// Initialize a new instance of `DateTime`.
  public init(
    year: Int32 = Int32(),
    month: Int32 = Int32(),
    day: Int32 = Int32(),
    hours: Int32 = Int32(),
    minutes: Int32 = Int32(),
    seconds: Int32 = Int32(),
    nanos: Int32 = Int32(),
    timeOffset: OneOf_TimeOffset? = nil,
  ) {
    self.year = year
    self.month = month
    self.day = day
    self.hours = hours
    self.minutes = minutes
    self.seconds = seconds
    self.nanos = nanos
    self.timeOffset = timeOffset
  }

  private enum CodingKeys: String, CodingKey {
    case year = "year"
    case month = "month"
    case day = "day"
    case hours = "hours"
    case minutes = "minutes"
    case seconds = "seconds"
    case nanos = "nanos"
    case utcOffset = "utcOffset"
    case timeZone = "timeZone"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.year = try container.decode(Int32.self, forKey: .year)
    self.month = try container.decode(Int32.self, forKey: .month)
    self.day = try container.decode(Int32.self, forKey: .day)
    self.hours = try container.decode(Int32.self, forKey: .hours)
    self.minutes = try container.decode(Int32.self, forKey: .minutes)
    self.seconds = try container.decode(Int32.self, forKey: .seconds)
    self.nanos = try container.decode(Int32.self, forKey: .nanos)

    var timeOffset: OneOf_TimeOffset? = nil
    let timeOffsetCheckAndSet = { (value: OneOf_TimeOffset) throws in
      if timeOffset != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'timeOffset'"))
      }
      timeOffset = value
    }
    if let utcOffset = try container.decodeIfPresent(
      GoogleCloudWkt.Duration?.self, forKey: .utcOffset)
    {
      try timeOffsetCheckAndSet(.utcOffset(utcOffset))
    }
    if let timeZone = try container.decodeIfPresent(TimeZone?.self, forKey: .timeZone) {
      try timeOffsetCheckAndSet(.timeZone(timeZone))
    }
    self.timeOffset = timeOffset
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.year, forKey: .year)
    try container.encode(self.month, forKey: .month)
    try container.encode(self.day, forKey: .day)
    try container.encode(self.hours, forKey: .hours)
    try container.encode(self.minutes, forKey: .minutes)
    try container.encode(self.seconds, forKey: .seconds)
    try container.encode(self.nanos, forKey: .nanos)

    if let choice = self.timeOffset {
      switch choice {
      case .utcOffset(let value):
        try container.encode(value, forKey: .utcOffset)
      case .timeZone(let value):
        try container.encode(value, forKey: .timeZone)
      }
    }
  }

  /// Optional. Specifies either the UTC offset or the time zone of the DateTime.
  /// Choose carefully between them, considering that time zone data may change
  /// in the future (for example, a country modifies their DST start/end dates,
  /// and future DateTimes in the affected range had already been stored).
  /// If omitted, the DateTime is considered to be in local time.
  public enum OneOf_TimeOffset: Codable, Equatable, Sendable {
    /// UTC offset. Must be whole seconds, between -18 hours and +18 hours.
    /// For example, a UTC offset of -4:00 would be represented as
    /// { seconds: -14400 }.
    indirect case utcOffset(GoogleCloudWkt.Duration?)
    /// Time zone.
    indirect case timeZone(TimeZone?)
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.type.DateTime" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
