// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Represents a day of the week.
public enum DayOfWeek: Codable, Equatable, Sendable {
  /// The day of the week is unspecified.
  case unspecified
  /// Monday
  case monday
  /// Tuesday
  case tuesday
  /// Wednesday
  case wednesday
  /// Thursday
  case thursday
  /// Friday
  case friday
  /// Saturday
  case saturday
  /// Sunday
  case sunday
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .monday: return 1
    case .tuesday: return 2
    case .wednesday: return 3
    case .thursday: return 4
    case .friday: return 5
    case .saturday: return 6
    case .sunday: return 7
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "DAY_OF_WEEK_UNSPECIFIED"
    case .monday: return "MONDAY"
    case .tuesday: return "TUESDAY"
    case .wednesday: return "WEDNESDAY"
    case .thursday: return "THURSDAY"
    case .friday: return "FRIDAY"
    case .saturday: return "SATURDAY"
    case .sunday: return "SUNDAY"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "DAY_OF_WEEK_UNSPECIFIED": self = .unspecified
    case "MONDAY": self = .monday
    case "TUESDAY": self = .tuesday
    case "WEDNESDAY": self = .wednesday
    case "THURSDAY": self = .thursday
    case "FRIDAY": self = .friday
    case "SATURDAY": self = .saturday
    case "SUNDAY": self = .sunday
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .monday
    case 2: self = .tuesday
    case 3: self = .wednesday
    case 4: self = .thursday
    case 5: self = .friday
    case 6: self = .saturday
    case 7: self = .sunday
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .monday: return try container.encode(1)
    case .tuesday: return try container.encode(2)
    case .wednesday: return try container.encode(3)
    case .thursday: return try container.encode(4)
    case .friday: return try container.encode(5)
    case .saturday: return try container.encode(6)
    case .sunday: return try container.encode(7)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
