// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Represents a day of the week.
public enum DayOfWeek: Int, Codable, Equatable, Sendable {
  case unspecified = 0
  case monday = 1
  case tuesday = 2
  case wednesday = 3
  case thursday = 4
  case friday = 5
  case saturday = 6
  case sunday = 7

  public init() {
    self = .unspecified
  }

  public var stringValue: String {
    switch self {
    case .unspecified: return "DAY_OF_WEEK_UNSPECIFIED"
    case .monday: return "MONDAY"
    case .tuesday: return "TUESDAY"
    case .wednesday: return "WEDNESDAY"
    case .thursday: return "THURSDAY"
    case .friday: return "FRIDAY"
    case .saturday: return "SATURDAY"
    case .sunday: return "SUNDAY"
    }
  }

  public init?(stringValue: String) {
    switch stringValue {
    case "DAY_OF_WEEK_UNSPECIFIED": self = .unspecified
    case "MONDAY": self = .monday
    case "TUESDAY": self = .tuesday
    case "WEDNESDAY": self = .wednesday
    case "THURSDAY": self = .thursday
    case "FRIDAY": self = .friday
    case "SATURDAY": self = .saturday
    case "SUNDAY": self = .sunday
    default: return nil
    }
  }
}
