// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a fraction in terms of a numerator divided by a denominator.
public struct Fraction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The numerator in the fraction, e.g. 2 in 2/3.
  public var numerator: Swift.Int64

  /// The value by which the numerator is divided, e.g. 3 in 2/3. Must be
  /// positive.
  public var denominator: Swift.Int64

  /// Initialize a new instance of `Fraction`.
  public init(
    numerator: Swift.Int64 = Swift.Int64(),
    denominator: Swift.Int64 = Swift.Int64(),
  ) {
    self.numerator = numerator
    self.denominator = denominator
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.type.Fraction" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
