// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An object that represents a latitude/longitude pair. This is expressed as a
/// pair of doubles to represent degrees latitude and degrees longitude. Unless
/// specified otherwise, this must conform to the
/// <a href="http://www.unoosa.org/pdf/icg/2012/template/WGS_84.pdf">WGS84
/// standard</a>. Values must be within normalized ranges.
public struct LatLng: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The latitude in degrees. It must be in the range [-90.0, +90.0].
  public var latitude: Double

  /// The longitude in degrees. It must be in the range [-180.0, +180.0].
  public var longitude: Double

  /// Initialize a new instance of `LatLng`.
  public init(
    latitude: Double = Double(),
    longitude: Double = Double(),
  ) {
    self.latitude = latitude
    self.longitude = longitude
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.type.LatLng" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
