// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An object representing a phone number, suitable as an API wire format.
///
/// This representation:
///
///  - should not be used for locale-specific formatting of a phone number, such
///    as "+1 (650) 253-0000 ext. 123"
///
///  - is not designed for efficient storage
///  - may not be suitable for dialing - specialized libraries (see references)
///    should be used to parse the number for that purpose
///
/// To do something meaningful with this number, such as format it for various
/// use-cases, convert it to an `i18n.phonenumbers.PhoneNumber` object first.
///
/// For instance, in Java this would be:
///
///     com.google.type.PhoneNumber wireProto =
///         com.google.type.PhoneNumber.newBuilder().build();
///     com.google.i18n.phonenumbers.Phonenumber.PhoneNumber phoneNumber =
///         PhoneNumberUtil.getInstance().parse(wireProto.getE164Number(), "ZZ");
///     if (!wireProto.getExtension().isEmpty()) {
///       phoneNumber.setExtension(wireProto.getExtension());
///     }
///
///  Reference(s):
///   - https://github.com/google/libphonenumber
public struct PhoneNumber: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The phone number's extension. The extension is not standardized in ITU
  /// recommendations, except for being defined as a series of numbers with a
  /// maximum length of 40 digits. Other than digits, some other dialing
  /// characters such as ',' (indicating a wait) or '#' may be stored here.
  ///
  /// Note that no regions currently use extensions with short codes, so this
  /// field is normally only set in conjunction with an E.164 number. It is held
  /// separately from the E.164 number to allow for short code extensions in the
  /// future.
  public var `extension`: Swift.String = Swift.String()

  /// Required.  Either a regular number, or a short code.  New fields may be
  /// added to the oneof below in the future, so clients should ignore phone
  /// numbers for which none of the fields they coded against are set.
  public var kind: OneOf_Kind? = nil

  /// Initialize a new instance of `PhoneNumber`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PhoneNumber().with { $0.e164Number = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case e164Number = "e164Number"
    case shortCode = "shortCode"
    case `extension` = "extension"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.`extension` = try container.decode(Swift.String.self, forKey: .`extension`)

    var kind: OneOf_Kind? = nil
    let kindCheckAndSet = {
      if kind != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'kind'"
          ))
      }
      kind = $0
    }
    if let e164Number = try container.decodeIfPresent(Swift.String.self, forKey: .e164Number) {
      try kindCheckAndSet(.e164Number(e164Number))
    }
    if let shortCode = try container.decodeIfPresent(
      PhoneNumber.ShortCode?.self, forKey: .shortCode)
    {
      try kindCheckAndSet(.shortCode(shortCode))
    }
    self.kind = kind
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.`extension`, forKey: .`extension`)

    if let choice = self.kind {
      switch choice {
      case .e164Number(let value):
        try container.encode(value, forKey: .e164Number)
      case .shortCode(let value):
        try container.encode(value, forKey: .shortCode)
      }
    }
  }

  /// An object representing a short code, which is a phone number that is
  /// typically much shorter than regular phone numbers and can be used to
  /// address messages in MMS and SMS systems, as well as for abbreviated dialing
  /// (For example "Text 611 to see how many minutes you have remaining on your
  /// plan.").
  ///
  /// Short codes are restricted to a region and are not internationally
  /// dialable, which means the same short code can exist in different regions,
  /// with different usage and pricing, even if those regions share the same
  /// country calling code (For example: US and CA).
  public struct ShortCode: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The BCP-47 region code of the location where calls to this
    /// short code can be made, such as "US" and "BB".
    ///
    /// Reference(s):
    ///  - http://www.unicode.org/reports/tr35/#unicode_region_subtag
    public var regionCode: Swift.String = Swift.String()

    /// Required. The short code digits, without a leading plus ('+') or country
    /// calling code. For example "611".
    public var number: Swift.String = Swift.String()

    /// Initialize a new instance of `ShortCode`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ShortCode().with { $0.regionCode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.type.PhoneNumber.ShortCode"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Required.  Either a regular number, or a short code.  New fields may be
  /// added to the oneof below in the future, so clients should ignore phone
  /// numbers for which none of the fields they coded against are set.
  public enum OneOf_Kind: Codable, Equatable, Sendable {
    /// The phone number, represented as a leading plus sign ('+'), followed by a
    /// phone number that uses a relaxed ITU E.164 format consisting of the
    /// country calling code (1 to 3 digits) and the subscriber number, with no
    /// additional spaces or formatting. For example:
    ///
    ///  - correct: "+15552220123"
    ///
    ///  - incorrect: "+1 (555) 222-01234 x123"
    ///
    /// The ITU E.164 format limits the latter to 12 digits, but in practice not
    /// all countries respect that, so we relax that restriction here.
    /// National-only numbers are not allowed.
    ///
    /// References:
    ///
    ///  - https://www.itu.int/rec/T-REC-E.164-201011-I
    ///
    ///  - https://en.wikipedia.org/wiki/E.164.
    ///
    ///  - https://en.wikipedia.org/wiki/List_of_country_calling_codes
    case e164Number(Swift.String)
    /// A short code.
    ///
    /// Reference(s):
    ///  - https://wikipedia.org/wiki/Short_code
    indirect case shortCode(PhoneNumber.ShortCode?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.type.PhoneNumber"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
