// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a time of day. The date and time zone are either not significant
/// or are specified elsewhere. An API may choose to allow leap seconds. Related
/// types are [google.type.Date][google.type.Date] and
/// `google.protobuf.Timestamp`.
///
/// [google.type.Date]: <doc:Date>
public struct TimeOfDay: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Hours of a day in 24 hour format. Must be greater than or equal to 0 and
  /// typically must be less than or equal to 23. An API may choose to allow the
  /// value "24:00:00" for scenarios like business closing time.
  public var hours: Swift.Int32

  /// Minutes of an hour. Must be greater than or equal to 0 and less than or
  /// equal to 59.
  public var minutes: Swift.Int32

  /// Seconds of a minute. Must be greater than or equal to 0 and typically must
  /// be less than or equal to 59. An API may allow the value 60 if it allows
  /// leap-seconds.
  public var seconds: Swift.Int32

  /// Fractions of seconds, in nanoseconds. Must be greater than or equal to 0
  /// and less than or equal to 999,999,999.
  public var nanos: Swift.Int32

  /// Initialize a new instance of `TimeOfDay`.
  public init(
    hours: Swift.Int32 = Swift.Int32(),
    minutes: Swift.Int32 = Swift.Int32(),
    seconds: Swift.Int32 = Swift.Int32(),
    nanos: Swift.Int32 = Swift.Int32(),
  ) {
    self.hours = hours
    self.minutes = minutes
    self.seconds = seconds
    self.nanos = nanos
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.type.TimeOfDay" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
