// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a time zone from the
/// [IANA Time Zone Database](https://www.iana.org/time-zones).
public struct TimeZone: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// IANA Time Zone Database time zone. For example "America/New_York".
  public var id: Swift.String

  /// Optional. IANA Time Zone Database version number. For example "2019a".
  public var version: Swift.String

  /// Initialize a new instance of `TimeZone`.
  public init(
    id: Swift.String = Swift.String(),
    version: Swift.String = Swift.String(),
  ) {
    self.id = id
    self.version = version
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.type.TimeZone" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
